version: "3.4"
services:
  mysql:
    container_name: mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: allyourbasearebelongtous
      MYSQL_USER: crm
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: crm_cadastro
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
    name: mysql_data
